### ISSUE TITLE
Make O+P dalco fixes persistant in ansible

### ISSUE THREAD

**Issue by mrnicegyu11** [ITISFoundation/osparc-ops-environments#362]
T.O. has done:

- updated the netplan config file on each host, so that the active network interface gets configured (the active interface has a different name on each host)
- updated the resolve.conf linking to get direct dns access without local caching rm /etc/resolve.conf; ln -s /run/systemd/resolve/resolv.conf /etc
- applied the new netplan config netplan apply

if I was the manager of these boxes, I would go for a slightly different approach when it comes to the netplan config, using the mac address to identify the interface and then actually set the name of the active interface to a fixed value on all cluster members as this makes configuration simpler than having different interface names all over the place:
```
network:
  version: 2
  renderer: networkd
  ethernets:
    primary-interface:
      match:
        macaddress: xx:xx:xx:xx:xx:xx
        set-name: net0
        emit-lldp: true
        addresses:
          - 172.16.8.x/23
        routes:
           - to: default
             via: 172.16.8.1
        nameservers:
          search:
            - s***g.com
          addresses:
            - 172.16.8.15 
```
in that way the primary interfrace would alway be called 'net0' 

CC @YuryHrytsuk
